//
// BusStopInformationAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class BusStopInformationAPI: APIBase {
    /**
     * enum for parameter format
     */
    public enum Format_getBusStops: String { 
        case Json = "json"
        case Xml = "xml"
    }

    /**
     * enum for parameter _operator
     */
    public enum Operator_getBusStops: String { 
        case Be = "BE"
        case Bac = "bac"
        case Kb = "KB"
        case Luas = "LUAS"
        case Ir = "ir"
    }

    /**
     Endpoint to retrieve bus stop information
     
     - parameter format: (query) If not provided JSON format will be used by default (optional)
     - parameter _operator: (query) If provided retrieves routes for the given operator (optional)
     - parameter stopid: (query) The bus stop id, if not provided all bus stops are returned (optional)
     - parameter stopname: (query) The stop name, only matching stops are returned (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getBusStops(format format: Format_getBusStops? = nil, _operator: Operator_getBusStops? = nil, stopid: String? = nil, stopname: String? = nil, completion: ((data: BusStopList?, error: ErrorType?) -> Void)) {
        getBusStopsWithRequestBuilder(format: format, _operator: _operator, stopid: stopid, stopname: stopname).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Endpoint to retrieve bus stop information
     - GET /busstopinformation
     - examples: [{contentType=application/json, example={
  "errormessage" : "aeiou",
  "numberofresults" : 5,
  "results" : [ {
    "fullnamelocalized" : "aeiou",
    "operators" : [ {
      "routes" : [ "aeiou" ],
      "name" : "ir"
    } ],
    "latitude" : "53.34642974",
    "stopid" : "HSTON",
    "fullname" : "aeiou",
    "shortnamelocalized" : "aeiou",
    "shortname" : "aeiou",
    "displaystopid" : "Dublin Heuston Station",
    "longitude" : "-6.294607473"
  } ],
  "errorcode" : "0",
  "timestamp" : "17/06/2017 11:44:35"
}}, {contentType=application/xml, example=<BusStopList>
  <errorcode>0</errorcode>
  <errormessage>string</errormessage>
  <numberofresults>5</numberofresults>
  <timestamp>17/06/2017 11:44:35</timestamp>
  <results>
  </results>
</BusStopList>}]
     - examples: [{contentType=application/json, example={
  "errormessage" : "aeiou",
  "numberofresults" : 5,
  "results" : [ {
    "fullnamelocalized" : "aeiou",
    "operators" : [ {
      "routes" : [ "aeiou" ],
      "name" : "ir"
    } ],
    "latitude" : "53.34642974",
    "stopid" : "HSTON",
    "fullname" : "aeiou",
    "shortnamelocalized" : "aeiou",
    "shortname" : "aeiou",
    "displaystopid" : "Dublin Heuston Station",
    "longitude" : "-6.294607473"
  } ],
  "errorcode" : "0",
  "timestamp" : "17/06/2017 11:44:35"
}}, {contentType=application/xml, example=<BusStopList>
  <errorcode>0</errorcode>
  <errormessage>string</errormessage>
  <numberofresults>5</numberofresults>
  <timestamp>17/06/2017 11:44:35</timestamp>
  <results>
  </results>
</BusStopList>}]
     
     - parameter format: (query) If not provided JSON format will be used by default (optional)
     - parameter _operator: (query) If provided retrieves routes for the given operator (optional)
     - parameter stopid: (query) The bus stop id, if not provided all bus stops are returned (optional)
     - parameter stopname: (query) The stop name, only matching stops are returned (optional)

     - returns: RequestBuilder<BusStopList> 
     */
    public class func getBusStopsWithRequestBuilder(format format: Format_getBusStops? = nil, _operator: Operator_getBusStops? = nil, stopid: String? = nil, stopname: String? = nil) -> RequestBuilder<BusStopList> {
        let path = "/busstopinformation"
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "format": format?.rawValue,
            "operator": _operator?.rawValue,
            "stopid": stopid,
            "stopname": stopname
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<BusStopList>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

}
