//
// OperatorInformationAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class OperatorInformationAPI: APIBase {
    /**
     * enum for parameter format
     */
    public enum Format_getOperators: String { 
        case Json = "json"
        case Xml = "xml"
    }

    /**
     Endpoint to retrieve information about route operators in the system
     
     - parameter format: (query) If not provided JSON format will be used by default (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getOperators(format format: Format_getOperators? = nil, completion: ((data: OperatorList?, error: ErrorType?) -> Void)) {
        getOperatorsWithRequestBuilder(format: format).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Endpoint to retrieve information about route operators in the system
     - GET /operatorinformation
     - examples: [{contentType=application/json, example={
  "errormessage" : "aeiou",
  "numberofresults" : 5,
  "results" : [ {
    "operatordescription" : "aeiou",
    "operatorreference" : "BE",
    "operatorname" : "Dublin Bus"
  } ],
  "errorcode" : "0",
  "timestamp" : "17/06/2017 11:44:35"
}}, {contentType=application/xml, example=<OperatorList>
  <errorcode>0</errorcode>
  <errormessage>string</errormessage>
  <numberofresults>5</numberofresults>
  <timestamp>17/06/2017 11:44:35</timestamp>
  <results>
  </results>
</OperatorList>}]
     - examples: [{contentType=application/json, example={
  "errormessage" : "aeiou",
  "numberofresults" : 5,
  "results" : [ {
    "operatordescription" : "aeiou",
    "operatorreference" : "BE",
    "operatorname" : "Dublin Bus"
  } ],
  "errorcode" : "0",
  "timestamp" : "17/06/2017 11:44:35"
}}, {contentType=application/xml, example=<OperatorList>
  <errorcode>0</errorcode>
  <errormessage>string</errormessage>
  <numberofresults>5</numberofresults>
  <timestamp>17/06/2017 11:44:35</timestamp>
  <results>
  </results>
</OperatorList>}]
     
     - parameter format: (query) If not provided JSON format will be used by default (optional)

     - returns: RequestBuilder<OperatorList> 
     */
    public class func getOperatorsWithRequestBuilder(format format: Format_getOperators? = nil) -> RequestBuilder<OperatorList> {
        let path = "/operatorinformation"
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "format": format?.rawValue
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<OperatorList>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

}
