/**
 * RTPI REST Web Services API
 * <p>RTPI REST Web Services API (<a href=\"https://goo.gl/s6NTJe\">RRWS API</a>) provides REST interface to retrieve information on real time bus information, timetables and bus stops. </p> <p>Each method available in RRWS API will be invoked using plain HTTP Request (GET method). Depending on parameters provided, result will be returned either in XML or JSON format (if format is not provided then JSON is used by default). Response will contain requested information (see method specification for details) and error status of the request.</p>  <h2>Error Codes</h2> <table> <tr><th>Error Code</th><th>Description</th></tr> <tr><td>0</td><td>Success</td></tr> <tr><td>1</td><td>No Results</td></tr> <tr><td>2</td><td>Missing Parameter</td></tr> <tr><td>3</td><td>Invalid Parameter</td></tr> <tr><td>4</td><td>Sceduled Downtime</td></tr> <tr><td>5</td><td>Unexpected System Error</td></tr> </table> <p>Error code is included in response for each message. For some error codes additional details will be provided in free text format (Error Message field).</p> 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#include "SWGRouteDetail.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGRouteDetail::SWGRouteDetail(QString* json) {
    init();
    this->fromJson(*json);
}

SWGRouteDetail::SWGRouteDetail() {
    init();
}

SWGRouteDetail::~SWGRouteDetail() {
    this->cleanup();
}

void
SWGRouteDetail::init() {
    operator = new QString("");
origin = new QString("");
originlocalized = new QString("");
destination = new QString("");
destinationlocalized = new QString("");
lastupdated = new QString("");
stops = new QList<SWGStop*>();
}

void
SWGRouteDetail::cleanup() {
    if(operator != NULL) {
        delete operator;
    }
if(origin != NULL) {
        delete origin;
    }
if(originlocalized != NULL) {
        delete originlocalized;
    }
if(destination != NULL) {
        delete destination;
    }
if(destinationlocalized != NULL) {
        delete destinationlocalized;
    }
if(lastupdated != NULL) {
        delete lastupdated;
    }
if(stops != NULL) {
        QList<SWGStop*>* arr = stops;
        foreach(SWGStop* o, *arr) {
            delete o;
        }
        delete stops;
    }
}

SWGRouteDetail*
SWGRouteDetail::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGRouteDetail::fromJsonObject(QJsonObject &pJson) {
    setValue(&operator, pJson["operator"], "QString", "QString");
setValue(&origin, pJson["origin"], "QString", "QString");
setValue(&originlocalized, pJson["originlocalized"], "QString", "QString");
setValue(&destination, pJson["destination"], "QString", "QString");
setValue(&destinationlocalized, pJson["destinationlocalized"], "QString", "QString");
setValue(&lastupdated, pJson["lastupdated"], "QString", "QString");
setValue(&stops, pJson["stops"], "QList", "SWGStop");
}

QString
SWGRouteDetail::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGRouteDetail::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    
    toJsonValue(QString("operator"), operator, obj, QString("QString"));
    
        

    
    toJsonValue(QString("origin"), origin, obj, QString("QString"));
    
        

    
    toJsonValue(QString("originlocalized"), originlocalized, obj, QString("QString"));
    
        

    
    toJsonValue(QString("destination"), destination, obj, QString("QString"));
    
        

    
    toJsonValue(QString("destinationlocalized"), destinationlocalized, obj, QString("QString"));
    
        

    
    toJsonValue(QString("lastupdated"), lastupdated, obj, QString("QString"));
    
        

    
    QList<SWGStop*>* stopsList = stops;
    QJsonArray stopsJsonArray;
    toJsonArray((QList<void*>*)stops, &stopsJsonArray, "stops", "SWGStop");

    obj->insert("stops", stopsJsonArray);
    

    return obj;
}

QString*
SWGRouteDetail::getOperator() {
    return operator;
}
void
SWGRouteDetail::setOperator(QString* operator) {
    this->operator = operator;
}

QString*
SWGRouteDetail::getOrigin() {
    return origin;
}
void
SWGRouteDetail::setOrigin(QString* origin) {
    this->origin = origin;
}

QString*
SWGRouteDetail::getOriginlocalized() {
    return originlocalized;
}
void
SWGRouteDetail::setOriginlocalized(QString* originlocalized) {
    this->originlocalized = originlocalized;
}

QString*
SWGRouteDetail::getDestination() {
    return destination;
}
void
SWGRouteDetail::setDestination(QString* destination) {
    this->destination = destination;
}

QString*
SWGRouteDetail::getDestinationlocalized() {
    return destinationlocalized;
}
void
SWGRouteDetail::setDestinationlocalized(QString* destinationlocalized) {
    this->destinationlocalized = destinationlocalized;
}

QString*
SWGRouteDetail::getLastupdated() {
    return lastupdated;
}
void
SWGRouteDetail::setLastupdated(QString* lastupdated) {
    this->lastupdated = lastupdated;
}

QList<SWGStop*>*
SWGRouteDetail::getStops() {
    return stops;
}
void
SWGRouteDetail::setStops(QList<SWGStop*>* stops) {
    this->stops = stops;
}



} /* namespace Swagger */

