/**
 * RTPI REST Web Services API
 * <p>RTPI REST Web Services API (<a href=\"https://goo.gl/s6NTJe\">RRWS API</a>) provides REST interface to retrieve information on real time bus information, timetables and bus stops. </p> <p>Each method available in RRWS API will be invoked using plain HTTP Request (GET method). Depending on parameters provided, result will be returned either in XML or JSON format (if format is not provided then JSON is used by default). Response will contain requested information (see method specification for details) and error status of the request.</p>  <h2>Error Codes</h2> <table> <tr><th>Error Code</th><th>Description</th></tr> <tr><td>0</td><td>Success</td></tr> <tr><td>1</td><td>No Results</td></tr> <tr><td>2</td><td>Missing Parameter</td></tr> <tr><td>3</td><td>Invalid Parameter</td></tr> <tr><td>4</td><td>Sceduled Downtime</td></tr> <tr><td>5</td><td>Unexpected System Error</td></tr> </table> <p>Error code is included in response for each message. For some error codes additional details will be provided in free text format (Error Message field).</p> 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#include "SWGStop.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGStop::SWGStop(QString* json) {
    init();
    this->fromJson(*json);
}

SWGStop::SWGStop() {
    init();
}

SWGStop::~SWGStop() {
    this->cleanup();
}

void
SWGStop::init() {
    stopid = new QString("");
displaystopid = new QString("");
shortname = new QString("");
shortnamelocalized = new QString("");
fullname = new QString("");
fullnamelocalized = new QString("");
latitude = new QString("");
longitude = new QString("");
operators = new QList<SWGRouteOperator*>();
}

void
SWGStop::cleanup() {
    if(stopid != NULL) {
        delete stopid;
    }
if(displaystopid != NULL) {
        delete displaystopid;
    }
if(shortname != NULL) {
        delete shortname;
    }
if(shortnamelocalized != NULL) {
        delete shortnamelocalized;
    }
if(fullname != NULL) {
        delete fullname;
    }
if(fullnamelocalized != NULL) {
        delete fullnamelocalized;
    }
if(latitude != NULL) {
        delete latitude;
    }
if(longitude != NULL) {
        delete longitude;
    }
if(operators != NULL) {
        QList<SWGRouteOperator*>* arr = operators;
        foreach(SWGRouteOperator* o, *arr) {
            delete o;
        }
        delete operators;
    }
}

SWGStop*
SWGStop::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGStop::fromJsonObject(QJsonObject &pJson) {
    setValue(&stopid, pJson["stopid"], "QString", "QString");
setValue(&displaystopid, pJson["displaystopid"], "QString", "QString");
setValue(&shortname, pJson["shortname"], "QString", "QString");
setValue(&shortnamelocalized, pJson["shortnamelocalized"], "QString", "QString");
setValue(&fullname, pJson["fullname"], "QString", "QString");
setValue(&fullnamelocalized, pJson["fullnamelocalized"], "QString", "QString");
setValue(&latitude, pJson["latitude"], "QString", "QString");
setValue(&longitude, pJson["longitude"], "QString", "QString");
setValue(&operators, pJson["operators"], "QList", "SWGRouteOperator");
}

QString
SWGStop::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGStop::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    
    toJsonValue(QString("stopid"), stopid, obj, QString("QString"));
    
        

    
    toJsonValue(QString("displaystopid"), displaystopid, obj, QString("QString"));
    
        

    
    toJsonValue(QString("shortname"), shortname, obj, QString("QString"));
    
        

    
    toJsonValue(QString("shortnamelocalized"), shortnamelocalized, obj, QString("QString"));
    
        

    
    toJsonValue(QString("fullname"), fullname, obj, QString("QString"));
    
        

    
    toJsonValue(QString("fullnamelocalized"), fullnamelocalized, obj, QString("QString"));
    
        

    
    toJsonValue(QString("latitude"), latitude, obj, QString("QString"));
    
        

    
    toJsonValue(QString("longitude"), longitude, obj, QString("QString"));
    
        

    
    QList<SWGRouteOperator*>* operatorsList = operators;
    QJsonArray operatorsJsonArray;
    toJsonArray((QList<void*>*)operators, &operatorsJsonArray, "operators", "SWGRouteOperator");

    obj->insert("operators", operatorsJsonArray);
    

    return obj;
}

QString*
SWGStop::getStopid() {
    return stopid;
}
void
SWGStop::setStopid(QString* stopid) {
    this->stopid = stopid;
}

QString*
SWGStop::getDisplaystopid() {
    return displaystopid;
}
void
SWGStop::setDisplaystopid(QString* displaystopid) {
    this->displaystopid = displaystopid;
}

QString*
SWGStop::getShortname() {
    return shortname;
}
void
SWGStop::setShortname(QString* shortname) {
    this->shortname = shortname;
}

QString*
SWGStop::getShortnamelocalized() {
    return shortnamelocalized;
}
void
SWGStop::setShortnamelocalized(QString* shortnamelocalized) {
    this->shortnamelocalized = shortnamelocalized;
}

QString*
SWGStop::getFullname() {
    return fullname;
}
void
SWGStop::setFullname(QString* fullname) {
    this->fullname = fullname;
}

QString*
SWGStop::getFullnamelocalized() {
    return fullnamelocalized;
}
void
SWGStop::setFullnamelocalized(QString* fullnamelocalized) {
    this->fullnamelocalized = fullnamelocalized;
}

QString*
SWGStop::getLatitude() {
    return latitude;
}
void
SWGStop::setLatitude(QString* latitude) {
    this->latitude = latitude;
}

QString*
SWGStop::getLongitude() {
    return longitude;
}
void
SWGStop::setLongitude(QString* longitude) {
    this->longitude = longitude;
}

QList<SWGRouteOperator*>*
SWGStop::getOperators() {
    return operators;
}
void
SWGStop::setOperators(QList<SWGRouteOperator*>* operators) {
    this->operators = operators;
}



} /* namespace Swagger */

