/**
 * RTPI REST Web Services API
 * <p>RTPI REST Web Services API (<a href=\"https://goo.gl/s6NTJe\">RRWS API</a>) provides REST interface to retrieve information on real time bus information, timetables and bus stops. </p> <p>Each method available in RRWS API will be invoked using plain HTTP Request (GET method). Depending on parameters provided, result will be returned either in XML or JSON format (if format is not provided then JSON is used by default). Response will contain requested information (see method specification for details) and error status of the request.</p>  <h2>Error Codes</h2> <table> <tr><th>Error Code</th><th>Description</th></tr> <tr><td>0</td><td>Success</td></tr> <tr><td>1</td><td>No Results</td></tr> <tr><td>2</td><td>Missing Parameter</td></tr> <tr><td>3</td><td>Invalid Parameter</td></tr> <tr><td>4</td><td>Sceduled Downtime</td></tr> <tr><td>5</td><td>Unexpected System Error</td></tr> </table> <p>Error code is included in response for each message. For some error codes additional details will be provided in free text format (Error Message field).</p> 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Operator;
import java.util.ArrayList;
import java.util.List;


/**
 * OperatorList
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-17T16:51:03.987+01:00")
public class OperatorList   {
  @SerializedName("errorcode")
  private String errorcode = null;

  @SerializedName("errormessage")
  private String errormessage = null;

  @SerializedName("numberofresults")
  private Integer numberofresults = null;

  @SerializedName("timestamp")
  private String timestamp = null;

  @SerializedName("results")
  private List<Operator> results = new ArrayList<Operator>();

  public OperatorList errorcode(String errorcode) {
    this.errorcode = errorcode;
    return this;
  }

   /**
   * Get errorcode
   * @return errorcode
  **/
  @ApiModelProperty(example = "0", value = "")
  public String getErrorcode() {
    return errorcode;
  }

  public void setErrorcode(String errorcode) {
    this.errorcode = errorcode;
  }

  public OperatorList errormessage(String errormessage) {
    this.errormessage = errormessage;
    return this;
  }

   /**
   * Get errormessage
   * @return errormessage
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getErrormessage() {
    return errormessage;
  }

  public void setErrormessage(String errormessage) {
    this.errormessage = errormessage;
  }

  public OperatorList numberofresults(Integer numberofresults) {
    this.numberofresults = numberofresults;
    return this;
  }

   /**
   * Get numberofresults
   * @return numberofresults
  **/
  @ApiModelProperty(example = "5", value = "")
  public Integer getNumberofresults() {
    return numberofresults;
  }

  public void setNumberofresults(Integer numberofresults) {
    this.numberofresults = numberofresults;
  }

  public OperatorList timestamp(String timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Get timestamp
   * @return timestamp
  **/
  @ApiModelProperty(example = "17/06/2017 11:44:35", value = "")
  public String getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(String timestamp) {
    this.timestamp = timestamp;
  }

  public OperatorList results(List<Operator> results) {
    this.results = results;
    return this;
  }

  public OperatorList addResultsItem(Operator resultsItem) {
    this.results.add(resultsItem);
    return this;
  }

   /**
   * Get results
   * @return results
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Operator> getResults() {
    return results;
  }

  public void setResults(List<Operator> results) {
    this.results = results;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OperatorList operatorList = (OperatorList) o;
    return Objects.equals(this.errorcode, operatorList.errorcode) &&
        Objects.equals(this.errormessage, operatorList.errormessage) &&
        Objects.equals(this.numberofresults, operatorList.numberofresults) &&
        Objects.equals(this.timestamp, operatorList.timestamp) &&
        Objects.equals(this.results, operatorList.results);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errorcode, errormessage, numberofresults, timestamp, results);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OperatorList {\n");
    
    sb.append("    errorcode: ").append(toIndentedString(errorcode)).append("\n");
    sb.append("    errormessage: ").append(toIndentedString(errormessage)).append("\n");
    sb.append("    numberofresults: ").append(toIndentedString(numberofresults)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

