<?php
/**
 * RealTimeBusInformationApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * RTPI REST Web Services API
 *
 * <p>RTPI REST Web Services API (<a href=\"https://goo.gl/s6NTJe\">RRWS API</a>) provides REST interface to retrieve information on real time bus information, timetables and bus stops. </p> <p>Each method available in RRWS API will be invoked using plain HTTP Request (GET method). Depending on parameters provided, result will be returned either in XML or JSON format (if format is not provided then JSON is used by default). Response will contain requested information (see method specification for details) and error status of the request.</p>  <h2>Error Codes</h2> <table> <tr><th>Error Code</th><th>Description</th></tr> <tr><td>0</td><td>Success</td></tr> <tr><td>1</td><td>No Results</td></tr> <tr><td>2</td><td>Missing Parameter</td></tr> <tr><td>3</td><td>Invalid Parameter</td></tr> <tr><td>4</td><td>Sceduled Downtime</td></tr> <tr><td>5</td><td>Unexpected System Error</td></tr> </table> <p>Error code is included in response for each message. For some error codes additional details will be provided in free text format (Error Message field).</p>
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * RealTimeBusInformationApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RealTimeBusInformationApi
{

    /**
     * API Client
     *
     * @var \Swagger\Client\ApiClient instance of the ApiClient
     */
    protected $apiClient;

    /**
     * Constructor
     *
     * @param \Swagger\Client\ApiClient|null $apiClient The api client to use
     */
    public function __construct(\Swagger\Client\ApiClient $apiClient = null)
    {
        if ($apiClient == null) {
            $apiClient = new ApiClient();
            $apiClient->getConfig()->setHost('https://data.dublinked.ie/cgi-bin/rtpi/');
        }

        $this->apiClient = $apiClient;
    }

    /**
     * Get API client
     *
     * @return \Swagger\Client\ApiClient get the API client
     */
    public function getApiClient()
    {
        return $this->apiClient;
    }

    /**
     * Set the API client
     *
     * @param \Swagger\Client\ApiClient $apiClient set the API client
     *
     * @return RealTimeBusInformationApi
     */
    public function setApiClient(\Swagger\Client\ApiClient $apiClient)
    {
        $this->apiClient = $apiClient;
        return $this;
    }

    /**
     * Operation getRealTimeBusInformation
     *
     * Endpoint to retrieve real time bus information
     *
     * @param string $stopid The bus stop id (required)
     * @param string $format If not provided JSON format will be used by default (optional)
     * @param string $operator If provided retrieves routes for the given operator (optional)
     * @param string $routeid The route identifier (optional)
     * @param string $maxresults The maximum number of results, if not provided system will limit the number of results depending on server configuration (optional)
     * @return \Swagger\Client\Model\RealTimeInformationList
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function getRealTimeBusInformation($stopid, $format = null, $operator = null, $routeid = null, $maxresults = null)
    {
        list($response) = $this->getRealTimeBusInformationWithHttpInfo($stopid, $format, $operator, $routeid, $maxresults);
        return $response;
    }

    /**
     * Operation getRealTimeBusInformationWithHttpInfo
     *
     * Endpoint to retrieve real time bus information
     *
     * @param string $stopid The bus stop id (required)
     * @param string $format If not provided JSON format will be used by default (optional)
     * @param string $operator If provided retrieves routes for the given operator (optional)
     * @param string $routeid The route identifier (optional)
     * @param string $maxresults The maximum number of results, if not provided system will limit the number of results depending on server configuration (optional)
     * @return Array of \Swagger\Client\Model\RealTimeInformationList, HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function getRealTimeBusInformationWithHttpInfo($stopid, $format = null, $operator = null, $routeid = null, $maxresults = null)
    {
        // verify the required parameter 'stopid' is set
        if ($stopid === null) {
            throw new \InvalidArgumentException('Missing the required parameter $stopid when calling getRealTimeBusInformation');
        }
        // parse inputs
        $resourcePath = "/realtimebusinformation";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = $this->apiClient->selectHeaderAccept(array('application/json', 'application/xml'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array('application/json','application/xml'));

        // query params
        if ($format !== null) {
            $queryParams['format'] = $this->apiClient->getSerializer()->toQueryValue($format);
        }
        // query params
        if ($operator !== null) {
            $queryParams['operator'] = $this->apiClient->getSerializer()->toQueryValue($operator);
        }
        // query params
        if ($stopid !== null) {
            $queryParams['stopid'] = $this->apiClient->getSerializer()->toQueryValue($stopid);
        }
        // query params
        if ($routeid !== null) {
            $queryParams['routeid'] = $this->apiClient->getSerializer()->toQueryValue($routeid);
        }
        // query params
        if ($maxresults !== null) {
            $queryParams['maxresults'] = $this->apiClient->getSerializer()->toQueryValue($maxresults);
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'GET',
                $queryParams,
                $httpBody,
                $headerParams,
                '\Swagger\Client\Model\RealTimeInformationList',
                '/realtimebusinformation'
            );

            return array($this->apiClient->getSerializer()->deserialize($response, '\Swagger\Client\Model\RealTimeInformationList', $httpHeader), $statusCode, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\RealTimeInformationList', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

}
