/**
 * RTPI REST Web Services API
 * <p>RTPI REST Web Services API (<a href=\"https://goo.gl/s6NTJe\">RRWS API</a>) provides REST interface to retrieve information on real time bus information, timetables and bus stops. </p> <p>Each method available in RRWS API will be invoked using plain HTTP Request (GET method). Depending on parameters provided, result will be returned either in XML or JSON format (if format is not provided then JSON is used by default). Response will contain requested information (see method specification for details) and error status of the request.</p>  <h2>Error Codes</h2> <table> <tr><th>Error Code</th><th>Description</th></tr> <tr><td>0</td><td>Success</td></tr> <tr><td>1</td><td>No Results</td></tr> <tr><td>2</td><td>Missing Parameter</td></tr> <tr><td>3</td><td>Invalid Parameter</td></tr> <tr><td>4</td><td>Sceduled Downtime</td></tr> <tr><td>5</td><td>Unexpected System Error</td></tr> </table> <p>Error code is included in response for each message. For some error codes additional details will be provided in free text format (Error Message field).</p> 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.reflect.TypeToken;
import java.lang.reflect.Type;
import java.util.List;
import io.swagger.client.model.*;

public class JsonUtil {
  public static GsonBuilder gsonBuilder;

  static {
    gsonBuilder = new GsonBuilder();
    gsonBuilder.serializeNulls();
    gsonBuilder.setDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ");
  }

  public static Gson getGson() {
    return gsonBuilder.create();
  }

  public static String serialize(Object obj){
    return getGson().toJson(obj);
  }

  public static <T> T deserializeToList(String jsonString, Class cls){
    return getGson().fromJson(jsonString, getListTypeForDeserialization(cls));
  }

  public static <T> T deserializeToObject(String jsonString, Class cls){
    return getGson().fromJson(jsonString, getTypeForDeserialization(cls));
  }

  public static Type getListTypeForDeserialization(Class cls) {
    String className = cls.getSimpleName();
    
    if ("BusStopList".equalsIgnoreCase(className)) {
      return new TypeToken<List<BusStopList>>(){}.getType();
    }
    
    if ("Operator".equalsIgnoreCase(className)) {
      return new TypeToken<List<Operator>>(){}.getType();
    }
    
    if ("OperatorList".equalsIgnoreCase(className)) {
      return new TypeToken<List<OperatorList>>(){}.getType();
    }
    
    if ("RealTimeInformation".equalsIgnoreCase(className)) {
      return new TypeToken<List<RealTimeInformation>>(){}.getType();
    }
    
    if ("RealTimeInformationList".equalsIgnoreCase(className)) {
      return new TypeToken<List<RealTimeInformationList>>(){}.getType();
    }
    
    if ("Route".equalsIgnoreCase(className)) {
      return new TypeToken<List<Route>>(){}.getType();
    }
    
    if ("RouteDetail".equalsIgnoreCase(className)) {
      return new TypeToken<List<RouteDetail>>(){}.getType();
    }
    
    if ("RouteDetailList".equalsIgnoreCase(className)) {
      return new TypeToken<List<RouteDetailList>>(){}.getType();
    }
    
    if ("RouteList".equalsIgnoreCase(className)) {
      return new TypeToken<List<RouteList>>(){}.getType();
    }
    
    if ("RouteOperator".equalsIgnoreCase(className)) {
      return new TypeToken<List<RouteOperator>>(){}.getType();
    }
    
    if ("Stop".equalsIgnoreCase(className)) {
      return new TypeToken<List<Stop>>(){}.getType();
    }
    
    if ("Timetable".equalsIgnoreCase(className)) {
      return new TypeToken<List<Timetable>>(){}.getType();
    }
    
    if ("TimetableList".equalsIgnoreCase(className)) {
      return new TypeToken<List<TimetableList>>(){}.getType();
    }
    
    return new TypeToken<List<Object>>(){}.getType();
  }

  public static Type getTypeForDeserialization(Class cls) {
    String className = cls.getSimpleName();
    
    if ("BusStopList".equalsIgnoreCase(className)) {
      return new TypeToken<BusStopList>(){}.getType();
    }
    
    if ("Operator".equalsIgnoreCase(className)) {
      return new TypeToken<Operator>(){}.getType();
    }
    
    if ("OperatorList".equalsIgnoreCase(className)) {
      return new TypeToken<OperatorList>(){}.getType();
    }
    
    if ("RealTimeInformation".equalsIgnoreCase(className)) {
      return new TypeToken<RealTimeInformation>(){}.getType();
    }
    
    if ("RealTimeInformationList".equalsIgnoreCase(className)) {
      return new TypeToken<RealTimeInformationList>(){}.getType();
    }
    
    if ("Route".equalsIgnoreCase(className)) {
      return new TypeToken<Route>(){}.getType();
    }
    
    if ("RouteDetail".equalsIgnoreCase(className)) {
      return new TypeToken<RouteDetail>(){}.getType();
    }
    
    if ("RouteDetailList".equalsIgnoreCase(className)) {
      return new TypeToken<RouteDetailList>(){}.getType();
    }
    
    if ("RouteList".equalsIgnoreCase(className)) {
      return new TypeToken<RouteList>(){}.getType();
    }
    
    if ("RouteOperator".equalsIgnoreCase(className)) {
      return new TypeToken<RouteOperator>(){}.getType();
    }
    
    if ("Stop".equalsIgnoreCase(className)) {
      return new TypeToken<Stop>(){}.getType();
    }
    
    if ("Timetable".equalsIgnoreCase(className)) {
      return new TypeToken<Timetable>(){}.getType();
    }
    
    if ("TimetableList".equalsIgnoreCase(className)) {
      return new TypeToken<TimetableList>(){}.getType();
    }
    
    return new TypeToken<Object>(){}.getType();
  }

};
