/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */
package io.swagger.client.api

import io.swagger.client.model.TimetableList
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object TimetableInformationApi {

  /**
   * 
   * 
   * Expected answers:
   *   code 200 : TimetableList (Success)
   * 
   * @param &#x60;type&#x60; value: week; Time table information is retrieved for the whole week
   * @param stopid The bus stop id, if not provided all bus stops are returned
   * @param routeid The route identifier
   * @param format If not provided JSON format will be used by default
   */
  def getTimeTable(&#x60;type&#x60;: String, stopid: String, routeid: String, format: Option[String] = None): ApiRequest[TimetableList] =
    ApiRequest[TimetableList](ApiMethods.GET, "https://data.dublinked.ie/cgi-bin/rtpi/", "/timetableinformation", "application/json")
      .withQueryParam("format", format)
      .withQueryParam("type", &#x60;type&#x60;)
      .withQueryParam("stopid", stopid)
      .withQueryParam("routeid", routeid)
      .withSuccessResponse[TimetableList](200)
      

}

