/**
 * RTPI REST Web Services API
 * <p>RTPI REST Web Services API (<a href=\"https://goo.gl/s6NTJe\">RRWS API</a>) provides REST interface to retrieve information on real time bus information, timetables and bus stops. </p> <p>Each method available in RRWS API will be invoked using plain HTTP Request (GET method). Depending on parameters provided, result will be returned either in XML or JSON format (if format is not provided then JSON is used by default). Response will contain requested information (see method specification for details) and error status of the request.</p>  <h2>Error Codes</h2> <table> <tr><th>Error Code</th><th>Description</th></tr> <tr><td>0</td><td>Success</td></tr> <tr><td>1</td><td>No Results</td></tr> <tr><td>2</td><td>Missing Parameter</td></tr> <tr><td>3</td><td>Invalid Parameter</td></tr> <tr><td>4</td><td>Sceduled Downtime</td></tr> <tr><td>5</td><td>Unexpected System Error</td></tr> </table> <p>Error code is included in response for each message. For some error codes additional details will be provided in free text format (Error Message field).</p> 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.RtpiRestWebServicesApi) {
      root.RtpiRestWebServicesApi = {};
    }
    root.RtpiRestWebServicesApi.RealTimeInformation = factory(root.RtpiRestWebServicesApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The RealTimeInformation model module.
   * @module model/RealTimeInformation
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>RealTimeInformation</code>.
   * @alias module:model/RealTimeInformation
   * @class
   */
  var exports = function() {
    var _this = this;


















  };

  /**
   * Constructs a <code>RealTimeInformation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RealTimeInformation} obj Optional instance to populate.
   * @return {module:model/RealTimeInformation} The populated <code>RealTimeInformation</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('arrivaldatetime')) {
        obj['arrivaldatetime'] = ApiClient.convertToType(data['arrivaldatetime'], 'String');
      }
      if (data.hasOwnProperty('duetime')) {
        obj['duetime'] = ApiClient.convertToType(data['duetime'], 'String');
      }
      if (data.hasOwnProperty('departuredatetime')) {
        obj['departuredatetime'] = ApiClient.convertToType(data['departuredatetime'], 'String');
      }
      if (data.hasOwnProperty('departureduetime')) {
        obj['departureduetime'] = ApiClient.convertToType(data['departureduetime'], 'String');
      }
      if (data.hasOwnProperty('scheduledarrivaldatetime')) {
        obj['scheduledarrivaldatetime'] = ApiClient.convertToType(data['scheduledarrivaldatetime'], 'String');
      }
      if (data.hasOwnProperty('scheduleddeparturedatetime')) {
        obj['scheduleddeparturedatetime'] = ApiClient.convertToType(data['scheduleddeparturedatetime'], 'String');
      }
      if (data.hasOwnProperty('destination')) {
        obj['destination'] = ApiClient.convertToType(data['destination'], 'String');
      }
      if (data.hasOwnProperty('destinationlocalized')) {
        obj['destinationlocalized'] = ApiClient.convertToType(data['destinationlocalized'], 'String');
      }
      if (data.hasOwnProperty('origin')) {
        obj['origin'] = ApiClient.convertToType(data['origin'], 'String');
      }
      if (data.hasOwnProperty('originlocalized')) {
        obj['originlocalized'] = ApiClient.convertToType(data['originlocalized'], 'String');
      }
      if (data.hasOwnProperty('direction')) {
        obj['direction'] = ApiClient.convertToType(data['direction'], 'String');
      }
      if (data.hasOwnProperty('operator')) {
        obj['operator'] = ApiClient.convertToType(data['operator'], 'String');
      }
      if (data.hasOwnProperty('additionalinformation')) {
        obj['additionalinformation'] = ApiClient.convertToType(data['additionalinformation'], 'String');
      }
      if (data.hasOwnProperty('lowfloorstatus')) {
        obj['lowfloorstatus'] = ApiClient.convertToType(data['lowfloorstatus'], 'String');
      }
      if (data.hasOwnProperty('route')) {
        obj['route'] = ApiClient.convertToType(data['route'], 'String');
      }
      if (data.hasOwnProperty('sourcetimestamp')) {
        obj['sourcetimestamp'] = ApiClient.convertToType(data['sourcetimestamp'], 'String');
      }
      if (data.hasOwnProperty('monitored')) {
        obj['monitored'] = ApiClient.convertToType(data['monitored'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} arrivaldatetime
   */
  exports.prototype['arrivaldatetime'] = undefined;
  /**
   * @member {String} duetime
   */
  exports.prototype['duetime'] = undefined;
  /**
   * @member {String} departuredatetime
   */
  exports.prototype['departuredatetime'] = undefined;
  /**
   * @member {String} departureduetime
   */
  exports.prototype['departureduetime'] = undefined;
  /**
   * @member {String} scheduledarrivaldatetime
   */
  exports.prototype['scheduledarrivaldatetime'] = undefined;
  /**
   * @member {String} scheduleddeparturedatetime
   */
  exports.prototype['scheduleddeparturedatetime'] = undefined;
  /**
   * @member {String} destination
   */
  exports.prototype['destination'] = undefined;
  /**
   * @member {String} destinationlocalized
   */
  exports.prototype['destinationlocalized'] = undefined;
  /**
   * @member {String} origin
   */
  exports.prototype['origin'] = undefined;
  /**
   * @member {String} originlocalized
   */
  exports.prototype['originlocalized'] = undefined;
  /**
   * @member {String} direction
   */
  exports.prototype['direction'] = undefined;
  /**
   * @member {String} operator
   */
  exports.prototype['operator'] = undefined;
  /**
   * @member {String} additionalinformation
   */
  exports.prototype['additionalinformation'] = undefined;
  /**
   * @member {String} lowfloorstatus
   */
  exports.prototype['lowfloorstatus'] = undefined;
  /**
   * @member {String} route
   */
  exports.prototype['route'] = undefined;
  /**
   * @member {String} sourcetimestamp
   */
  exports.prototype['sourcetimestamp'] = undefined;
  /**
   * @member {String} monitored
   */
  exports.prototype['monitored'] = undefined;



  return exports;
}));


