# coding: utf-8

"""
    RTPI REST Web Services API

    <p>RTPI REST Web Services API (<a href=\"https://goo.gl/s6NTJe\">RRWS API</a>) provides REST interface to retrieve information on real time bus information, timetables and bus stops. </p> <p>Each method available in RRWS API will be invoked using plain HTTP Request (GET method). Depending on parameters provided, result will be returned either in XML or JSON format (if format is not provided then JSON is used by default). Response will contain requested information (see method specification for details) and error status of the request.</p>  <h2>Error Codes</h2> <table> <tr><th>Error Code</th><th>Description</th></tr> <tr><td>0</td><td>Success</td></tr> <tr><td>1</td><td>No Results</td></tr> <tr><td>2</td><td>Missing Parameter</td></tr> <tr><td>3</td><td>Invalid Parameter</td></tr> <tr><td>4</td><td>Sceduled Downtime</td></tr> <tr><td>5</td><td>Unexpected System Error</td></tr> </table> <p>Error code is included in response for each message. For some error codes additional details will be provided in free text format (Error Message field).</p> 

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

# import models into sdk package
from .models.bus_stop_list import BusStopList
from .models.operator import Operator
from .models.operator_list import OperatorList
from .models.real_time_information import RealTimeInformation
from .models.real_time_information_list import RealTimeInformationList
from .models.route import Route
from .models.route_detail import RouteDetail
from .models.route_detail_list import RouteDetailList
from .models.route_list import RouteList
from .models.route_operator import RouteOperator
from .models.stop import Stop
from .models.timetable import Timetable
from .models.timetable_list import TimetableList

# import apis into sdk package
from .apis.bus_stop_information_api import BusStopInformationApi
from .apis.operator_information_api import OperatorInformationApi
from .apis.real_time_bus_information_api import RealTimeBusInformationApi
from .apis.route_detail_information_api import RouteDetailInformationApi
from .apis.route_information_api import RouteInformationApi
from .apis.timetable_information_api import TimetableInformationApi

# import ApiClient
from .api_client import ApiClient

from .configuration import Configuration

configuration = Configuration()
