=begin comment

RTPI REST Web Services API

<p>RTPI REST Web Services API (<a href=\"https://goo.gl/s6NTJe\">RRWS API</a>) provides REST interface to retrieve information on real time bus information, timetables and bus stops. </p> <p>Each method available in RRWS API will be invoked using plain HTTP Request (GET method). Depending on parameters provided, result will be returned either in XML or JSON format (if format is not provided then JSON is used by default). Response will contain requested information (see method specification for details) and error status of the request.</p>  <h2>Error Codes</h2> <table> <tr><th>Error Code</th><th>Description</th></tr> <tr><td>0</td><td>Success</td></tr> <tr><td>1</td><td>No Results</td></tr> <tr><td>2</td><td>Missing Parameter</td></tr> <tr><td>3</td><td>Invalid Parameter</td></tr> <tr><td>4</td><td>Sceduled Downtime</td></tr> <tr><td>5</td><td>Unexpected System Error</td></tr> </table> <p>Error code is included in response for each message. For some error codes additional details will be provided in free text format (Error Message field).</p> 

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
package WWW::SwaggerClient::Object::RealTimeInformation;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base ("Class::Accessor", "Class::Data::Inheritable");


#
#
#
# NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
# REF: https://github.com/swagger-api/swagger-codegen
#

=begin comment

RTPI REST Web Services API

<p>RTPI REST Web Services API (<a href=\"https://goo.gl/s6NTJe\">RRWS API</a>) provides REST interface to retrieve information on real time bus information, timetables and bus stops. </p> <p>Each method available in RRWS API will be invoked using plain HTTP Request (GET method). Depending on parameters provided, result will be returned either in XML or JSON format (if format is not provided then JSON is used by default). Response will contain requested information (see method specification for details) and error status of the request.</p>  <h2>Error Codes</h2> <table> <tr><th>Error Code</th><th>Description</th></tr> <tr><td>0</td><td>Success</td></tr> <tr><td>1</td><td>No Results</td></tr> <tr><td>2</td><td>Missing Parameter</td></tr> <tr><td>3</td><td>Invalid Parameter</td></tr> <tr><td>4</td><td>Sceduled Downtime</td></tr> <tr><td>5</td><td>Unexpected System Error</td></tr> </table> <p>Error code is included in response for each message. For some error codes additional details will be provided in free text format (Error Message field).</p> 

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('swagger_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {}); 
__PACKAGE__->mk_classdata('class_documentation' => {});

# new object
sub new { 
    my ($class, %args) = @_; 

	my $self = bless {}, $class;
	
	foreach my $attribute (keys %{$class->attribute_map}) {
		my $args_key = $class->attribute_map->{$attribute};
		$self->$attribute( $args{ $args_key } );
	}
	
	return $self;
}  

# return perl hash
sub to_hash {
    return decode_json(JSON->new->convert_blessed->encode( shift ));
}

# used by JSON for serialization
sub TO_JSON { 
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            $_data->{$self->attribute_map->{$_key}} = $self->{$_key};
        }
    }
    return $_data;
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use swagger_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->swagger_types} ) {
    	my $_json_attribute = $self->attribute_map->{$_key}; 
        if ($_type =~ /^array\[/i) { # array
            my $_subclass = substr($_type, 6, -1);
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
        	$log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }
  
    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);
        
    if ($type eq 'DateTime') {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double', 'string', 'boolean'))) {
        return $data;
    } else { # hash(model)
        my $_instance = eval "WWW::SwaggerClient::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}



__PACKAGE__->class_documentation({description => '',
                                  class => 'RealTimeInformation',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'arrivaldatetime' => {
    	datatype => 'string',
    	base_name => 'arrivaldatetime',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'duetime' => {
    	datatype => 'string',
    	base_name => 'duetime',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'departuredatetime' => {
    	datatype => 'string',
    	base_name => 'departuredatetime',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'departureduetime' => {
    	datatype => 'string',
    	base_name => 'departureduetime',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'scheduledarrivaldatetime' => {
    	datatype => 'string',
    	base_name => 'scheduledarrivaldatetime',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'scheduleddeparturedatetime' => {
    	datatype => 'string',
    	base_name => 'scheduleddeparturedatetime',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'destination' => {
    	datatype => 'string',
    	base_name => 'destination',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'destinationlocalized' => {
    	datatype => 'string',
    	base_name => 'destinationlocalized',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'origin' => {
    	datatype => 'string',
    	base_name => 'origin',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'originlocalized' => {
    	datatype => 'string',
    	base_name => 'originlocalized',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'direction' => {
    	datatype => 'string',
    	base_name => 'direction',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'operator' => {
    	datatype => 'string',
    	base_name => 'operator',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'additionalinformation' => {
    	datatype => 'string',
    	base_name => 'additionalinformation',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'lowfloorstatus' => {
    	datatype => 'string',
    	base_name => 'lowfloorstatus',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'route' => {
    	datatype => 'string',
    	base_name => 'route',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'sourcetimestamp' => {
    	datatype => 'string',
    	base_name => 'sourcetimestamp',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'monitored' => {
    	datatype => 'string',
    	base_name => 'monitored',
    	description => '',
    	format => '',
    	read_only => '',
    		},
});

__PACKAGE__->swagger_types( {
    'arrivaldatetime' => 'string',
    'duetime' => 'string',
    'departuredatetime' => 'string',
    'departureduetime' => 'string',
    'scheduledarrivaldatetime' => 'string',
    'scheduleddeparturedatetime' => 'string',
    'destination' => 'string',
    'destinationlocalized' => 'string',
    'origin' => 'string',
    'originlocalized' => 'string',
    'direction' => 'string',
    'operator' => 'string',
    'additionalinformation' => 'string',
    'lowfloorstatus' => 'string',
    'route' => 'string',
    'sourcetimestamp' => 'string',
    'monitored' => 'string'
} );

__PACKAGE__->attribute_map( {
    'arrivaldatetime' => 'arrivaldatetime',
    'duetime' => 'duetime',
    'departuredatetime' => 'departuredatetime',
    'departureduetime' => 'departureduetime',
    'scheduledarrivaldatetime' => 'scheduledarrivaldatetime',
    'scheduleddeparturedatetime' => 'scheduleddeparturedatetime',
    'destination' => 'destination',
    'destinationlocalized' => 'destinationlocalized',
    'origin' => 'origin',
    'originlocalized' => 'originlocalized',
    'direction' => 'direction',
    'operator' => 'operator',
    'additionalinformation' => 'additionalinformation',
    'lowfloorstatus' => 'lowfloorstatus',
    'route' => 'route',
    'sourcetimestamp' => 'sourcetimestamp',
    'monitored' => 'monitored'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
