/**
 * RTPI REST Web Services API
 * <p>RTPI REST Web Services API (<a href=\"https://goo.gl/s6NTJe\">RRWS API</a>) provides REST interface to retrieve information on real time bus information, timetables and bus stops. </p> <p>Each method available in RRWS API will be invoked using plain HTTP Request (GET method). Depending on parameters provided, result will be returned either in XML or JSON format (if format is not provided then JSON is used by default). Response will contain requested information (see method specification for details) and error status of the request.</p>  <h2>Error Codes</h2> <table> <tr><th>Error Code</th><th>Description</th></tr> <tr><td>0</td><td>Success</td></tr> <tr><td>1</td><td>No Results</td></tr> <tr><td>2</td><td>Missing Parameter</td></tr> <tr><td>3</td><td>Invalid Parameter</td></tr> <tr><td>4</td><td>Sceduled Downtime</td></tr> <tr><td>5</td><td>Unexpected System Error</td></tr> </table> <p>Error code is included in response for each message. For some error codes additional details will be provided in free text format (Error Message field).</p> 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.api;

import io.swagger.client.ApiCallback;
import io.swagger.client.ApiClient;
import io.swagger.client.ApiException;
import io.swagger.client.ApiResponse;
import io.swagger.client.Configuration;
import io.swagger.client.Pair;
import io.swagger.client.ProgressRequestBody;
import io.swagger.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;

import io.swagger.client.model.TimetableList;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TimetableInformationApi {
    private ApiClient apiClient;

    public TimetableInformationApi() {
        this(Configuration.getDefaultApiClient());
    }

    public TimetableInformationApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /* Build call for getTimeTable */
    private com.squareup.okhttp.Call getTimeTableCall(String type, String stopid, String routeid, String format, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // verify the required parameter 'type' is set
        if (type == null) {
            throw new ApiException("Missing the required parameter 'type' when calling getTimeTable(Async)");
        }
        
        // verify the required parameter 'stopid' is set
        if (stopid == null) {
            throw new ApiException("Missing the required parameter 'stopid' when calling getTimeTable(Async)");
        }
        
        // verify the required parameter 'routeid' is set
        if (routeid == null) {
            throw new ApiException("Missing the required parameter 'routeid' when calling getTimeTable(Async)");
        }
        

        // create path and map variables
        String localVarPath = "/timetableinformation".replaceAll("\\{format\\}","json");

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        if (format != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "format", format));
        if (type != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "type", type));
        if (stopid != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "stopid", stopid));
        if (routeid != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "routeid", routeid));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json", "application/xml"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json", "application/xml"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    /**
     * Endpoint to retrieve timetable information
     * 
     * @param type value: week; Time table information is retrieved for the whole week (required)
     * @param stopid The bus stop id, if not provided all bus stops are returned (required)
     * @param routeid The route identifier (required)
     * @param format If not provided JSON format will be used by default (optional)
     * @return TimetableList
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public TimetableList getTimeTable(String type, String stopid, String routeid, String format) throws ApiException {
        ApiResponse<TimetableList> resp = getTimeTableWithHttpInfo(type, stopid, routeid, format);
        return resp.getData();
    }

    /**
     * Endpoint to retrieve timetable information
     * 
     * @param type value: week; Time table information is retrieved for the whole week (required)
     * @param stopid The bus stop id, if not provided all bus stops are returned (required)
     * @param routeid The route identifier (required)
     * @param format If not provided JSON format will be used by default (optional)
     * @return ApiResponse&lt;TimetableList&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<TimetableList> getTimeTableWithHttpInfo(String type, String stopid, String routeid, String format) throws ApiException {
        com.squareup.okhttp.Call call = getTimeTableCall(type, stopid, routeid, format, null, null);
        Type localVarReturnType = new TypeToken<TimetableList>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Endpoint to retrieve timetable information (asynchronously)
     * 
     * @param type value: week; Time table information is retrieved for the whole week (required)
     * @param stopid The bus stop id, if not provided all bus stops are returned (required)
     * @param routeid The route identifier (required)
     * @param format If not provided JSON format will be used by default (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call getTimeTableAsync(String type, String stopid, String routeid, String format, final ApiCallback<TimetableList> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = getTimeTableCall(type, stopid, routeid, format, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<TimetableList>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
