/**
 * RTPI REST Web Services API
 * <p>RTPI REST Web Services API (<a href=\"https://goo.gl/s6NTJe\">RRWS API</a>) provides REST interface to retrieve information on real time bus information, timetables and bus stops. </p> <p>Each method available in RRWS API will be invoked using plain HTTP Request (GET method). Depending on parameters provided, result will be returned either in XML or JSON format (if format is not provided then JSON is used by default). Response will contain requested information (see method specification for details) and error status of the request.</p>  <h2>Error Codes</h2> <table> <tr><th>Error Code</th><th>Description</th></tr> <tr><td>0</td><td>Success</td></tr> <tr><td>1</td><td>No Results</td></tr> <tr><td>2</td><td>Missing Parameter</td></tr> <tr><td>3</td><td>Invalid Parameter</td></tr> <tr><td>4</td><td>Sceduled Downtime</td></tr> <tr><td>5</td><td>Unexpected System Error</td></tr> </table> <p>Error code is included in response for each message. For some error codes additional details will be provided in free text format (Error Message field).</p> 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import io.swagger.client.model.RealTimeInformation;
import java.util.*;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class RealTimeInformationList  {
  
  @SerializedName("errorcode")
  private String errorcode = null;
  @SerializedName("errormessage")
  private String errormessage = null;
  @SerializedName("numberofresults")
  private Integer numberofresults = null;
  @SerializedName("stopid")
  private String stopid = null;
  @SerializedName("timestamp")
  private String timestamp = null;
  @SerializedName("results")
  private List<RealTimeInformation> results = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getErrorcode() {
    return errorcode;
  }
  public void setErrorcode(String errorcode) {
    this.errorcode = errorcode;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getErrormessage() {
    return errormessage;
  }
  public void setErrormessage(String errormessage) {
    this.errormessage = errormessage;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getNumberofresults() {
    return numberofresults;
  }
  public void setNumberofresults(Integer numberofresults) {
    this.numberofresults = numberofresults;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getStopid() {
    return stopid;
  }
  public void setStopid(String stopid) {
    this.stopid = stopid;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getTimestamp() {
    return timestamp;
  }
  public void setTimestamp(String timestamp) {
    this.timestamp = timestamp;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<RealTimeInformation> getResults() {
    return results;
  }
  public void setResults(List<RealTimeInformation> results) {
    this.results = results;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RealTimeInformationList realTimeInformationList = (RealTimeInformationList) o;
    return (errorcode == null ? realTimeInformationList.errorcode == null : errorcode.equals(realTimeInformationList.errorcode)) &&
        (errormessage == null ? realTimeInformationList.errormessage == null : errormessage.equals(realTimeInformationList.errormessage)) &&
        (numberofresults == null ? realTimeInformationList.numberofresults == null : numberofresults.equals(realTimeInformationList.numberofresults)) &&
        (stopid == null ? realTimeInformationList.stopid == null : stopid.equals(realTimeInformationList.stopid)) &&
        (timestamp == null ? realTimeInformationList.timestamp == null : timestamp.equals(realTimeInformationList.timestamp)) &&
        (results == null ? realTimeInformationList.results == null : results.equals(realTimeInformationList.results));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (errorcode == null ? 0: errorcode.hashCode());
    result = 31 * result + (errormessage == null ? 0: errormessage.hashCode());
    result = 31 * result + (numberofresults == null ? 0: numberofresults.hashCode());
    result = 31 * result + (stopid == null ? 0: stopid.hashCode());
    result = 31 * result + (timestamp == null ? 0: timestamp.hashCode());
    result = 31 * result + (results == null ? 0: results.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class RealTimeInformationList {\n");
    
    sb.append("  errorcode: ").append(errorcode).append("\n");
    sb.append("  errormessage: ").append(errormessage).append("\n");
    sb.append("  numberofresults: ").append(numberofresults).append("\n");
    sb.append("  stopid: ").append(stopid).append("\n");
    sb.append("  timestamp: ").append(timestamp).append("\n");
    sb.append("  results: ").append(results).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
